### ISSUE TITLE
Better Error Reporting for Missing Properties

### ISSUE THREAD

**Issue by mbateman** [neomatrix369/RESTAPIUnifier#87]
Unit Tests fail with for example the following output when properties are missing: 

java.lang.IllegalStateException: IO Exception occurred
    at org.neomatrix369.apiworld.util.Utils.readPropertyFrom(Utils.java:117)
    at org.neomatrix369.examples.muzutv.BaseMuzu.<init>(BaseMuzu.java:56)
    at org.neomatrix369.examples.muzutv.data.Artist.<init>(Artist.java:41)

**Comment by mbateman** [comment]
Is this sufficient?

**Comment by neomatrix369** [comment]
The requirement here is a bit more specific - missing properties - how could we make it easier and inform the reader about missing properties ?
